# Prometheus configuration for VNPT Money Chatbot
global:
  scrape_interval: 5s
  evaluation_interval: 5s

# Remote write to Grafana Cloud
remote_write:
  - url: https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/prom/push
    basic_auth:
      username: "2948135"
      password: "${GRAFANA_CLOUD_API_TOKEN}"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  
  - job_name: 'vnpt-chatbot'
    static_configs:
      - targets: ['host.docker.internal:8001']
        labels:
          env: 'production'
    metrics_path: '/metrics/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s
